#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'AFModule_Example' do
  pod 'AFModule', :path => '../'
  pod 'YYText'
  target 'AFModule_Tests' do
    inherit! :search_paths

    
  end
end
